# Generated by Django 5.2.16 on 2026-07-17 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Ürün Adı')),
                ('description', models.TextField(verbose_name='Ürün Açıklaması')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ürün Fiyatı')),
                ('stock', models.PositiveIntegerField(default=5, verbose_name='Stok Miktarı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ürün Durumu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ürün Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ürün Güncellenme Tarihi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.category')),
            ],
            options={
                'verbose_name_plural': 'Ürünler',
                'ordering': ['-created_at'],
            },
        ),
    ]
